
import type { Product } from './types';

export const products: Product[] = [
  {
    id: 10,
    name: 'Paket Buket Hamper',
    description: 'Terdiri dari 10 wedhang, termasuk box, kartu ucapan, dan dekorasi cantik untuk orang tersayang.',
    price: 185000,
    image: 'https://ik.imagekit.io/hrctvvb3m/Untitled%20design%20(15).png',
    category: 'Paket Spesial',
    tag: 'Edisi Terbatas',
    isSpecialOffer: true,
  },
  {
    id: 11,
    name: 'Paket Bundling 2 Buket Hamper',
    description: 'Lebih hemat! Dapatkan 2 Paket Buket Hamper hanya dengan 350rb.',
    price: 350000,
    image: 'https://ik.imagekit.io/hrctvvb3m/Untitled%20design%20(15).png',
    category: 'Paket Spesial',
    tag: 'Hemat 20rb',
    isSpecialOffer: true,
  },
  {
    id: 12,
    name: 'Kurma Energy Ball (Isi 4)',
    description: 'Camilan sehat padat nutrisi berbahan dasar kurma pilihan. Cocok untuk booster energi saat puasa.',
    price: 45000,
    image: 'https://ik.imagekit.io/hrctvvb3m/Untitled%20design%20(18).png',
    category: 'Paket Spesial',
    tag: 'Isi 4 Pcs',
    isSpecialOffer: true,
  },
  {
    id: 13,
    name: 'Kurma Energy Ball (Isi 6)',
    description: 'Camilan sehat padat nutrisi berbahan dasar kurma pilihan. Lebih banyak, lebih puas!',
    price: 55000,
    image: 'https://ik.imagekit.io/hrctvvb3m/Untitled%20design%20(18).png',
    category: 'Paket Spesial',
    tag: 'Isi 6 Pcs',
    isSpecialOffer: true,
  },
  {
    id: 1,
    name: 'Minyak JSR Aromatik',
    description: 'Minyak esensial murni dengan aroma menenangkan.',
    price: 89000,
    image: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?q=80&w=1974&auto=format&fit=crop',
    category: 'Herbal Oil',
    tag: 'New Arrival',
  },
  {
    id: 2,
    name: 'Madu Murni Randu',
    description: 'Madu murni dari nektar bunga randu pilihan.',
    price: 120000,
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?q=80&w=1974&auto=format&fit=crop',
    category: 'Superfood',
    tag: 'New Arrival',
  },
  {
    id: 3,
    name: 'Teh Celup Bunga Telang',
    description: 'Teh herbal bunga telang kaya antioksidan.',
    price: 35000,
    image: 'https://images.unsplash.com/photo-1597481499750-3e6b22637e12?q=80&w=1974&auto=format&fit=crop',
    category: 'Wedhang',
    tag: 'New Arrival',
  },
  {
    id: 4,
    name: 'Dried Fruit Mix',
    description: 'Campuran buah kering pilihan tanpa pemanis buatan.',
    price: 55000,
    image: 'https://images.unsplash.com/photo-1596591606975-97ee5cef3a1e?q=80&w=1974&auto=format&fit=crop',
    category: 'Snacks',
    tag: 'New Arrival',
  },
  {
    id: 5,
    name: 'Snack Plizstop Pedas',
    description: 'Perpaduan gurih dengan sensasi pedas yang bikin nagih.',
    price: 33000,
    image: 'https://ik.imagekit.io/hrctvvb3m/Untitled%20design%20(1).png',
    category: 'Snack Plizstop',
    tag: 'Isi 70gr',
  },
  {
    id: 2,
    name: 'Snack Plizstop Original',
    description: 'Rasa gurih renyah klasik, aman dan cocok dinikmati semua usia.',
    price: 33000,
    image: 'https://ik.imagekit.io/hrctvvb3m/Untitled%20design%20(1).png',
    category: 'Snack Plizstop',
    tag: 'Isi 70gr',
  },
  {
    id: 3,
    name: 'Wedhang Super Rempah',
    description: 'Best Seller! Perpaduan 6 rempah lengkap untuk kesehatan menyeluruh.',
    price: 100000,
    image: 'https://ik.imagekit.io/hrctvvb3m/2.png',
    category: 'Wedhang Cafe JSR',
    tag: '1 Box isi 10 Sachet',
    isBestSeller: true,
    isHighlight: true,
  },
  {
    id: 4,
    name: 'Wedhang Detoks Lemak',
    description: 'Kunyit & Lemon. Melancarkan metabolisme dan bantu program diet.',
    price: 100000,
    image: 'https://ik.imagekit.io/hrctvvb3m/3.png',
    category: 'Wedhang Cafe JSR',
    tag: '1 Box isi 10 Sachet',
  },
  {
    id: 5,
    name: 'Wedhang Imun Booster',
    description: 'Kunyit, Lengkuas, Jahe. Ikhtiar menjaga daya tahan tubuh agar tidak mudah sakit.',
    price: 100000,
    image: 'https://ik.imagekit.io/hrctvvb3m/6.png',
    category: 'Wedhang Cafe JSR',
    tag: '1 Box isi 10 Sachet',
  },
  {
    id: 6,
    name: 'Wedhang Lambung Ceria',
    description: 'Secang, Jahe, Pandan. Menenangkan lambung dan mengurangi kembung.',
    price: 100000,
    image: 'https://ik.imagekit.io/hrctvvb3m/4.png',
    category: 'Wedhang Cafe JSR',
    tag: '1 Box isi 10 Sachet',
  },
  {
    id: 7,
    name: 'Wedhang Napas Lega',
    description: 'Bunga Telang, Pandan. Melegakan pernapasan dan tenggorokan.',
    price: 100000,
    image: 'https://ik.imagekit.io/hrctvvb3m/8.png',
    category: 'Wedhang Cafe JSR',
    tag: '1 Box isi 10 Sachet',
  },
  {
    id: 8,
    name: 'Wedhang Radang Hilang',
    description: 'Kunyit & Jintan Hitam. Membantu meredakan peradangan/nyeri di tubuh.',
    price: 100000,
    image: 'https://ik.imagekit.io/hrctvvb3m/7.png',
    category: 'Wedhang Cafe JSR',
    tag: '1 Box isi 10 Sachet',
  },
  {
    id: 9,
    name: 'Wedhang Flu Hilang Hangat Menyapa',
    description: 'Jahe & Kayu Manis. Membantu meredakan gejala flu dan pilek.',
    price: 100000,
    image: 'https://ik.imagekit.io/hrctvvb3m/5.png',
    category: 'Wedhang Cafe JSR',
    tag: '1 Box isi 10 Sachet',
  },
];
