
import type { Product } from './types';

export const products: Product[] = [
  {
    id: 10,
    name: 'Wedhang To Go Varian MIX',
    description: 'Edisi spesial! Box ini berisi semua varian Wedhang To Go terbaik kami. Rasakan semua manfaatnya dalam satu paket praktis.',
    price: 100000,
    image: 'https://ik.imagekit.io/hrctvvb3m/Untitled%20design%20(10).png',
    category: 'Wedhang Cafe JSR',
    tag: '1 Box isi 10 Sachet',
  },
  {
    id: 1,
    name: 'Snack Plizstop Pedas',
    description: 'Perpaduan gurih dengan sensasi pedas yang bikin nagih.',
    price: 33000,
    image: 'https://ik.imagekit.io/hrctvvb3m/Untitled%20design%20(1).png',
    category: 'Snack Plizstop',
    tag: 'Isi 70gr',
  },
  {
    id: 2,
    name: 'Snack Plizstop Original',
    description: 'Rasa gurih renyah klasik, aman dan cocok dinikmati semua usia.',
    price: 33000,
    image: 'https://ik.imagekit.io/hrctvvb3m/Untitled%20design%20(1).png',
    category: 'Snack Plizstop',
    tag: 'Isi 70gr',
  },
  {
    id: 3,
    name: 'Wedhang Super Rempah',
    description: 'Best Seller! Perpaduan 6 rempah lengkap untuk kesehatan menyeluruh.',
    price: 100000,
    image: 'https://ik.imagekit.io/hrctvvb3m/2.png',
    category: 'Wedhang Cafe JSR',
    tag: '1 Box isi 10 Sachet',
    isBestSeller: true,
  },
  {
    id: 4,
    name: 'Wedhang Detoks Lemak',
    description: 'Kunyit & Lemon. Melancarkan metabolisme dan bantu program diet.',
    price: 100000,
    image: 'https://ik.imagekit.io/hrctvvb3m/3.png',
    category: 'Wedhang Cafe JSR',
    tag: '1 Box isi 10 Sachet',
  },
  {
    id: 5,
    name: 'Wedhang Imun Booster',
    description: 'Kunyit, Lengkuas, Jahe. Ikhtiar menjaga daya tahan tubuh agar tidak mudah sakit.',
    price: 100000,
    image: 'https://ik.imagekit.io/hrctvvb3m/6.png',
    category: 'Wedhang Cafe JSR',
    tag: '1 Box isi 10 Sachet',
  },
  {
    id: 6,
    name: 'Wedhang Lambung Ceria',
    description: 'Secang, Jahe, Pandan. Menenangkan lambung dan mengurangi kembung.',
    price: 100000,
    image: 'https://ik.imagekit.io/hrctvvb3m/4.png',
    category: 'Wedhang Cafe JSR',
    tag: '1 Box isi 10 Sachet',
  },
  {
    id: 7,
    name: 'Wedhang Napas Lega',
    description: 'Bunga Telang, Pandan. Melegakan pernapasan dan tenggorokan.',
    price: 100000,
    image: 'https://ik.imagekit.io/hrctvvb3m/8.png',
    category: 'Wedhang Cafe JSR',
    tag: '1 Box isi 10 Sachet',
  },
  {
    id: 8,
    name: 'Wedhang Radang Hilang',
    description: 'Kunyit & Jintan Hitam. Membantu meredakan peradangan/nyeri di tubuh.',
    price: 100000,
    image: 'https://ik.imagekit.io/hrctvvb3m/7.png',
    category: 'Wedhang Cafe JSR',
    tag: '1 Box isi 10 Sachet',
  },
  {
    id: 9,
    name: 'Wedhang Flu Hilang Hangat Menyapa',
    description: 'Jahe & Kayu Manis. Membantu meredakan gejala flu dan pilek.',
    price: 100000,
    image: 'https://ik.imagekit.io/hrctvvb3m/5.png',
    category: 'Wedhang Cafe JSR',
    tag: '1 Box isi 10 Sachet',
  },
];